import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { UserProvider } from "./context/UserContext";
import { ProductProvider } from "./context/ProductContext";
import { PageProvider } from "./context/PageContext";
import "../bulma/bulma.scss";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserProvider>
          <ProductProvider>
            <PageProvider>{children}</PageProvider>
          </ProductProvider>
        </UserProvider>
      </body>
    </html>
  );
}
